use_frameworks!
inhibit_all_warnings!

target "StoreKitCompanionDemo iOS" do
  platform :ios, "8.0"
  pod 'Alamofire', '~> 3.1.5'
end

target "StoreKitCompanionDemo OSX" do
  platform :osx, "10.10"
  pod 'Alamofire', '~> 3.1.5'
end